**Introduction to NumPy**

In [1]:
import numpy as np

**Problem 1**

In [2]:
def my_array1(x, y):
    return A @ B

A = np.array([ [3, -1, 4], [1, 5, -9] ])
B = np.array([ [2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3] ])
my_array1(A, B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

**Problem 2**

In [3]:
# Write a function that defines the following matrix as a NumPy array.
def my_array2(x):
    return (-A @ -A @ -A) + (9 * (A @ A)) - (15 * A)

A = np.array([ [3, 1, 4], [1, 5, 9], [-5, 3, 1] ])
my_array2(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**Problem 3**

In [4]:
def my_array3(x, y):
    result3 = x @ y @ x
    result3 = result3.astype(np.int64)
    return result3

A = np.ones((7, 7))
A2 = np.triu(A)
B = np.full((7, 7), 6)
B2 = np.triu(B) - 1

my_array3(A2, B2)

array([[ -1,   4,  15,  32,  55,  84, 119],
       [ -6,  -6,   0,  12,  30,  54,  84],
       [ -5, -10,  -9,  -2,  11,  30,  55],
       [ -4,  -8, -12, -10,  -2,  12,  32],
       [ -3,  -6,  -9, -12,  -9,   0,  15],
       [ -2,  -4,  -6,  -8, -10,  -6,   4],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -1]], dtype=int64)

**Problem 4**

In [5]:
def array_copy(input_array):
    x = np.copy(input_array)
    mask = x < 0
    x[mask] = 0
    return x

A = np.array([ [2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3] ])
array_copy(A)

array([[2, 6, 0, 3],
       [5, 0, 9, 7],
       [9, 0, 0, 0]])

**Problem 5**

In [6]:
def block_matrix():
    A = np.arange(6).reshape(3, 2).T
    B3 = np.full((3, 3), 3)
    B = np.tril(B3)
    C = np.diag([-2, -2, -2])
    I = np.eye(3)
    vert1 = np.vstack((np.zeros((3,3)), A, B))
    vert2 = np.vstack((A.T, np.zeros((2,2)), np.zeros((3,2))))
    vert3 = np.vstack((I, np.zeros((2,3)), C))
    block = np.hstack((vert1, vert2, vert3))
    block = block.astype(np.int64)
    return block

block_matrix()

array([[ 0,  0,  0,  0,  1,  1,  0,  0],
       [ 0,  0,  0,  2,  3,  0,  1,  0],
       [ 0,  0,  0,  4,  5,  0,  0,  1],
       [ 0,  2,  4,  0,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0, -2,  0,  0],
       [ 3,  3,  0,  0,  0,  0, -2,  0],
       [ 3,  3,  3,  0,  0,  0,  0, -2]], dtype=int64)

**Problem 6**

In [7]:
def new_mat(A):
    x = A.sum(axis=1)
    return(A.T/x).T

new_mat(A)

array([[ 0.33333333,  1.        , -0.83333333,  0.5       ],
       [ 0.38461538, -0.61538462,  0.69230769,  0.53846154],
       [ 9.        , -3.        , -2.        , -3.        ]])

**Problem 7**

In [8]:
grid = np.load(r"C:\Users\danie\BootCamp2018\Computation\Wk1_PyIntro\grid.npy")
def prod4(grid):
    horizmax = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    vertmax = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    rdiagmax = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1:,2:-1] * grid[3:,3:])
    ldiagmax = np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1:,1:-2] * grid[3:,:-3])
    max_value = max(horizmax, vertmax, rdiagmax, ldiagmax)
    return max_value

print(prod4(grid))

70600674
